name: Production Tests

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    environment: staging_environment
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/checkout@v2

      - name: Install dependensies
        run: npm install

  test:
    environment: staging_environment
    needs: [build]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/setup-node@v2.3.0
        with:
          node-version: 16.x
          cache: 'npm'

      - uses: actions/checkout@v2

      - name: Install dependensies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e
